### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by jakub-olczyk** [mzucker/noteshrink#1]
@mzucker 
I am afraid that there are parts of the world that cannot use your program simply because there is no LICENSE file or any other information about the legal status of the code. 
I would recommend GPLv3 or MIT license. But there are [more options depending on what aspect of the legal status of the code is your concern](http://choosealicense.com/).

Cheers!

**Comment by avoidr** [comment]
I would also be glad to see your program become free software. I think it would be a good contribution to the community.

**Comment by mzucker** [comment]
Added MIT license in ab3178d – had totally forgotten to think about this when preparing the repo/writeup.
