### ISSUE TITLE
SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by juh2** [mzucker/noteshrink#10]
I downloaded the release 0.1 installed the requirements via pip and run make.

```
make
mkdir -p example_output && \
cd example_output && \
../noteshrink.py -O -g -w -s 20 -v 30 -o notesA.pdf ../examples/notesA*.jpg
  File "../noteshrink.py", line 159
    print '  running "{}"...'.format(cmd),
                            ^
SyntaxError: invalid syntax
makefile:9: die Regel für Ziel „example_output/notesA.pdf“ scheiterte
make: *** [example_output/notesA.pdf] Fehler 1
```

**Comment by juh2** [comment]
I tried it with Python 3 and obviously the software depends on Python 2. So perhaps turn this issue into a feature request: Make it Python 3 compliant.

**Comment by mzucker** [comment]
I believe we are now Python 3 compliant as of 0701e13724a7d7087d9eb711cc0be6e387620711 -- but I don't know how to update on PyPI -- if anyone can provide me instructions, I will increment the version number and re-upload.

**Comment by michi88** [comment]
This is helpful: https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

**Comment by mzucker** [comment]
Think it's re-uploaded, not sure if my modifications to setup.py were correct; feel free to try again.

**Comment by LEXUSAPI** [comment]
Good to me !  officelens will die

**Comment by mzucker** [comment]
Thanks!
@juh2 can you confirm whether the latest PyPi fix worked for you?

**Comment by juh2** [comment]
I pip installed it in my py3 env and ran it on the examples. It worked. Thanks!

**Comment by mzucker** [comment]
Great, closing this issue.
