### ISSUE TITLE
Old documents

### ISSUE THREAD

**Issue by tsulej** [mzucker/noteshrink#12]
Hi, I was trying to run you app on old documents taken from church to enhance readability. Unfortunately can't find best settings to remove noisy background.

Two of them are here:
https://www.dropbox.com/sh/u3noc0dkd17r0a0/AABR0yDH07qG63oDMtENL8FBa?dl=0

I was trying with settings:
-p up to 50
-n up to 128
-v down to 5
-s down to 5
and result wasn't satisfactory

Could you treat it as a case study?

**Comment by mzucker** [comment]
Hi tsulej - documents like this are challenging for a couple of reasons. The noise you pointed out is one, and the subtle gradient across the entire image is another. I've tried to work with similar documents and found that noteshrink just doesn't perform well on them. I'd advise you to look into some type of adaptive thresholding or band-stop filtering to process these images.
