### ISSUE TITLE
Warning: Error opening image

### ISSUE THREAD

**Issue by 1stdevfriend** [mzucker/noteshrink#29]
warning: error opening C:\Users\Kartikey
warning: error opening Kushwah\Downloads\Compressed\noteshrink-master\image.jpg
running PDF command "convert  output.pdf"...
Invalid drive specification.
warning: PDF command failed

**Comment by piyusharma95** [comment]
Please specify the link to the image with which you are facing the error.

**Comment by DiegoFaFe** [comment]
@SwampDolphin97 as i stated on #15 it's cause it collides with a windows' command (https://technet.microsoft.com/en-us/library/bb490885.aspx)

Just use it like this:
`python noteshrink.py -c "magick convert %i %o" IMAGE1 [IMAGE2 ...]`

Or get #30 changes

**Comment by 1stdevfriend** [comment]
Yes. Fixed!
