### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by kpym** [mzucker/noteshrink#41]
I wanted just to warn you that I have seen your code in [another repo](https://github.com/gosha20777/NoteShrink). The [noteshrink.py](https://github.com/gosha20777/NoteShrink/blob/master/PythonModule/noteshrink.py) looks the same, except that we can find `Created by Georgy Perevozchikov (gosha20777) 2018.` on [line 7](https://github.com/gosha20777/NoteShrink/blob/82832054859047ba7b6b4c81efd3755811ecfc34/PythonModule/noteshrink.py#L7).

**Comment by zvezdochiot** [comment]
https://github.com/mzucker/noteshrink/blob/master/LICENSE.txt and https://github.com/gosha20777/NoteShrink/blob/master/LICENSE . What is the problem?

**Comment by kpym** [comment]
Well if you do not see a problem just close this issue ;)
For me the problem is not the reuse but the mention `Created by ...`.

**Comment by mzucker** [comment]
@zvezdochiot this is not how copyright works. It's not good practice to change the creator name in MIT-licensed code. See for instance https://softwareengineering.stackexchange.com/questions/386582/altering-author-names-in-mit-license

You were licensed to distribute the software as long as you distributed the original copyright notice. Instead you modified the original copyright notice by replacing my name with yours. 

Please correct this by restoring my name to the LICENSE file.

**Comment by zvezdochiot** [comment]
@mzucker say:
>Instead you modified the original copyright notice by replacing my name with yours.

Wrong. I am an outside observer. I’m trying to understand why the noise is. And I can’t understand. Always interested in distributing my code, consider any obstacles to be hostile. I don’t understand your motivation at all.

**Comment by mzucker** [comment]
@zvezdochiot Sorry if you're not the author of https://github.com/gosha20777/NoteShrink/blob/master/LICENSE - I assumed that since you were the one replying, you were the author. In any event, I'll be filing an issue on that repo separately. Closing this issue. Thanks very much to @kpym for alerting me of this.
