### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by daneah** [mzucker/noteshrink#8]
I recently found `noteshrink` and I'm fond of its utility! Thanks for giving it to the world!

In order to confidently make `noteshrink` compatible with Python 3 (per issue #4), introduction of unit tests would be beneficial. This will provide a baseline to compare behaviors as well as help with alteration of existing features/introduction of new features over time.

I would like to help with this, but I want to feel this out before I get the horse too far ahead of the cart! The code structure seems amenable to unit testing for the most part.

**Comment by mzucker** [comment]
I think that unit testing is a great idea for larger projects, less so small, single-file utilities like `noteshrink`. The project is MIT-licensed, so feel free to fork your own version and add unit tests to it as you see fit. In the meantime, I'm going to close this issue, bearing in mind that #4 will likely require fairly minor changes.

Thanks for your feedback!

**Comment by daneah** [comment]
That's fair—was going to follow up with a pull request for the changes I'd made to get Python 3 working on my end but I see I've been beaten to it!
